version: '3.1'
services:
  app:
    container_name: springapp
    image: iswarya12/springapp-book
    build: ./
    ports:
      - "8081:8080"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=book