apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-spring-deployment
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: springapp
          image: iswarya12/springapp-book
          ports:
            - containerPort: 8080
